### PR TITLE
The Asciidoctor extension for updating Fulcro live examples 

### PR DESCRIPTION
**Pull request by abhi18av**
@awkay , here's the PR that culminates the discussion done in https://github.com/fulcrologic/fulcro-developer-guide/pull/12  and the resulting experiment here https://github.com/abhi18av/FulcroExamplesAsciidoc 

As of now I've only changed the very first `example-1` and just to be sure, could you please take it for a spin and confirm that it works fine in all other output formats? 

I'll transform all other examples and update the `Makefile` as soon as you give a go-ahead.

### CODE REVIEW

**Comment by abhi18av** [comment]
To test it out, you'd need to run the following 

```
$ asciidoctor -o DevelopersGuide.html -b html5  -r asciidoctor-diagram DevelopersGuide.adoc

```

**Comment by awkay** [comment]
I had to add a few more `-r` options, but yes, that looks good.

2 things (I think both were unintentional):

- Please don't rename the dev guide
- Please don't check in .DS_store files

Thanks!

**Comment by awkay** [comment]
Actually, one more thing, probably more the ruby extension itself into src...perhaps `src/ruby`?

**Comment by abhi18av** [comment]
@awkay, good to hear about this extension rendering correctly.

- The `DevelopersGuide.adoc` has been renamed to `DevelopersGuideSource.adoc` because on running the extension, it will write the `DevelopersGuide.adoc` with fully expanded `Asciidoc` forms for the `$example$` forms. Another solution was to just overwrite the `DevelopersGuide.adoc` itself with the expanded file, which doesn't feel elegant at all.

Let me know what you feel is better.

- The `.DS_store` is definitely a mistake 😅 

- For `src/ruby`, sure roger that.

**Comment by abhi18av** [comment]
I've updated the PR for the new `src/ruby` location but for the `.DS_Store` I don't quite know how to completely remove it from the history. Do you have any pointers here?

**Comment by awkay** [comment]
just rm it, I'll squash the history, so it won't show up.

**Comment by awkay** [comment]
On the rename: generated files that are an output step (output of preprocessing) should go someplace else (e.g. /tmp or something).  DeveloperGuide.adoc is the base source to edit...anything else is just a stage in output and should be generally ignorable.
I was running it by adding `-r` for the two files you made, and that seemed to generate the HTML fine...I didn't notice it overwriting the original, but perhaps I wasn't paying attn.

**Comment by awkay** [comment]
yeah, it was overwriting...but why do you even have this:

```
    reader.unshift_all(replacement_lines)
    # TODO Remove the generation of the intermediate Expanded file
    File.open("DevelopersGuide.adoc", "w") { |file| file.puts reader.lines}

```
???

**Comment by awkay** [comment]
```
asciidoctor -o docs/DevelopersGuide.html -b html5 -r asciidoctor-diagram -r ./register-fulcro-examples.rb -r ./fulcro-examples-extension.rb DevelopersGuide.adoc
```

works fine without writing that file.

**Comment by abhi18av** [comment]
Hmm, that's suprising 🤔  Maybe it's because I was experimenting without the `-r asciidoctor-diagram` which might have influenced this. Anyways, good to know that it works without the intermediate file - thanks for the tip regarding `/tmp` 👍 

I'm in the middle of transforming the examples, in between the classes, this should complete in around 8 hours.

**Comment by abhi18av** [comment]
Have deleted the `src/.DS_Store` as well.

**Comment by abhi18av** [comment]
An update, all the examples have been ported and for more examples which might be added in future I've created a list here already https://github.com/abhi18av/FulcroExamplesAsciidoc/blob/master/ReadMe.adoc

**Comment by awkay** [comment]
Thanks!

**Comment by abhi18av** [comment]
You're most welcome @awkay 👍

**Pull request merged**
